# Generated by Django 4.1.4 on 2022-12-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description10',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi10"),
        ),
        migrations.AddField(
            model_name='word',
            name='description2',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi2"),
        ),
        migrations.AddField(
            model_name='word',
            name='description3',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi3"),
        ),
        migrations.AddField(
            model_name='word',
            name='description4',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi4"),
        ),
        migrations.AddField(
            model_name='word',
            name='description5',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi5"),
        ),
        migrations.AddField(
            model_name='word',
            name='description6',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi6"),
        ),
        migrations.AddField(
            model_name='word',
            name='description7',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi7"),
        ),
        migrations.AddField(
            model_name='word',
            name='description8',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi8"),
        ),
        migrations.AddField(
            model_name='word',
            name='description9',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi9"),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name="So'z izohi"),
        ),
    ]
